GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/6685a7e88ccad8464e308e7f

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Groucho",
    "number": "123-123-1231"
}